import Link from "next/link";
import Image from "next/image";
import { ArrowRight, Github, Sparkles } from "lucide-react";
import { site } from "@/lib/site";

export function Hero() {
  return (
    <section className="relative overflow-hidden">
      {/* Subtle dotted backdrop, like printed paper. */}
      <div
        aria-hidden
        className="pointer-events-none absolute inset-0 opacity-[0.12]"
        style={{
          backgroundImage:
            "radial-gradient(circle at 1px 1px, rgba(15,23,42,0.5) 1px, transparent 0)",
          backgroundSize: "16px 16px"
        }}
      />

      <div className="container relative pt-20 pb-24 md:pt-28 md:pb-32">
        <div className="mx-auto grid max-w-6xl grid-cols-1 items-center gap-14 lg:grid-cols-[1.05fr_0.95fr]">
          {/* ---------- Copy ---------- */}
          <div>
            <span className="chip">
              <Sparkles className="h-3.5 w-3.5 text-indigo-600" />
              Open-source · Research preview
            </span>

            <h1 className="mt-6 font-serif text-display">
              Turn your lessons
              <br />
              into <span className="ink-underline">Manga</span>.
            </h1>

            <p className="mt-6 max-w-prose text-lead text-muted">
              {site.name} is an open-source AI learning studio for teachers. Drop in any
              lesson — an AP chapter, a homework PDF, a topic in your head —
              and get back a six-page manga your students will actually
              <em> finish reading</em>.
            </p>

            <div className="mt-8 flex flex-wrap items-center gap-3">
              <Link
                href={site.links.studio}
                className="btn-primary"
              >
                Launch Studio
                <ArrowRight className="h-4 w-4" />
              </Link>
              <Link href="/#showcase" className="btn-secondary">
                See examples
              </Link>
              <Link
                href={site.links.github}
                target="_blank"
                rel="noreferrer"
                className="btn-secondary"
              >
                <Github className="h-4 w-4" />
                Self-host on GitHub
              </Link>
            </div>

            <dl className="mt-10 grid max-w-md grid-cols-3 gap-6 text-sm">
              <Stat n="6 pages" l="per lesson" />
              <Stat n="Invite" l="controlled access" />
              <Stat n="Server" l="keys stay hidden" />
            </dl>
          </div>

          {/* ---------- Visual ---------- */}
          <HeroVisual />
        </div>
      </div>
    </section>
  );
}

function Stat({ n, l }: { n: string; l: string }) {
  return (
    <div>
      <dt className="font-serif text-2xl font-semibold text-ink">{n}</dt>
      <dd className="text-xs uppercase tracking-[0.12em] text-muted">{l}</dd>
    </div>
  );
}

function HeroVisual() {
  // Stack of three comic pages, fanned out, with a subtle paper shadow.
  const pages = [
    site.showcase.unit1.pages[0],
    site.showcase.unit1.pages[2],
    site.showcase.unit1.pages[4]
  ];
  return (
    <div className="relative mx-auto aspect-[5/6] w-full max-w-md">
      {pages.map((src, i) => {
        const rot = [-7, 0, 6][i];
        const tx  = [-32, 0, 32][i];
        const ty  = [16, 0, 14][i];
        const z   = [10, 30, 20][i];
        return (
          <div
            key={src}
            style={{
              transform: `translate(${tx}px, ${ty}px) rotate(${rot}deg)`,
              zIndex: z
            }}
            className="absolute inset-0 origin-center overflow-hidden rounded-paper border border-rule bg-white shadow-paper"
          >
            <Image
              src={src}
              alt={`ComicLearn sample page ${i + 1}`}
              fill
              sizes="(min-width: 1024px) 28rem, 80vw"
              className="object-cover"
              priority={i === 1}
            />
          </div>
        );
      })}
      {/* Caption badge */}
      <div className="absolute -bottom-6 left-1/2 z-40 -translate-x-1/2 whitespace-nowrap rounded-full bg-ink px-4 py-1.5 text-xs font-medium tracking-wide text-paper shadow-paper">
        AP Calc · Limits · generated by ComicLearn
      </div>
    </div>
  );
}
