import type { Metadata } from "next";
import Link from "next/link";
import { Github, MessageCircle, ArrowRight } from "lucide-react";
import { Showcase } from "@/components/showcase";
import { site } from "@/lib/site";

export const metadata: Metadata = {
  title: "Live demo",
  description: `See finished lessons generated by ${site.name}.`
};

export default function DemoPage() {
  return (
    <>
      <section className="container pt-20 md:pt-28">
        <div className="mx-auto max-w-3xl">
          <p className="page-no">§ Demo</p>
          <h1 className="mt-4 font-serif text-display">A real lesson, end-to-end.</h1>
          <p className="mt-6 max-w-prose text-lead text-muted">
            Below are two AP Calculus units generated by {site.name} — Unit 1.1
            (Limits) and Unit 1.2 (Derivatives). Both were created from a single
            prompt; nothing has been hand-edited.
          </p>

          <div className="mt-7 flex flex-wrap gap-3">
            <Link
              href={site.links.github + "#quickstart"}
              target="_blank"
              rel="noreferrer"
              className="btn-primary"
            >
              Run it yourself in 60s
              <ArrowRight className="h-4 w-4" />
            </Link>
            <Link
              href={site.links.discord}
              target="_blank"
              rel="noreferrer"
              className="btn-secondary"
            >
              <MessageCircle className="h-4 w-4" />
              Ask in Discord
            </Link>
            <Link
              href={site.links.github}
              target="_blank"
              rel="noreferrer"
              className="btn-secondary"
            >
              <Github className="h-4 w-4" />
              Read the source
            </Link>
          </div>
        </div>
      </section>

      <Showcase />
    </>
  );
}
